config/routes.rb
Rails.application.routes.draw do
  root to: 'application#root'
  get 'clear', to: 'application#clear'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def root
    if params[:code].present?
      set_ss_token
      redirect_to root_path and return
    end
    if cookies[:ss_access_tokens].present?
      @teams = {}
      @all_tokens = JSON.parse(cookies[:ss_access_tokens].gsub('=>', ':'))
      @all_tokens.each do |token|
        response = list_stars(token.second, { count: (params[:count] || 1000), page: (params[:page] || 1) })
        if response.error
          @error = response.error
        else
          @teams[token.first] = response.items
        end
      end
    end
  end

  def clear
    cookies.delete :ss_access_tokens
    redirect_to root_path
  end

  private

  def set_ss_token
    client = Slack::Web::Client.new
    resp = client.oauth_access(client_id: ENV['SLACK_APP_CLIENT_ID'], client_secret: ENV['SLACK_APP_CLIENT_SECRET'], code: params[:code])
    if resp.ok == true
      all_tokens = cookies[:ss_access_tokens].present? ? JSON.parse(cookies[:ss_access_tokens].gsub('=>', ':')) : {}
      cookies[:ss_access_tokens] = {
        value: all_tokens.merge(resp.team_name => resp.access_token),
        expires: 1.year.from_now
      }
    end
  rescue Slack::Web::Api::Error
    @error = 'Slack token already used. Try again.'
  end

  def list_stars(token, options)
    client = Slack::Web::Client.new(token: token)
    client.stars_list(options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_text(text)
    Rinku.auto_link(simple_format(Slack::Messages::Formatting.unescape(text)), :all, 'target="_blank"').html_safe
  end
end

app/views/application/root.slim
- if @teams.present?
  - @teams.each do |team|
    - if team.second.present?
      - team.second.each do |msg|
        - if msg['type'] == "message"
          .panel.panel-default
            .panel-body
              p
                strong=> msg['message']['user'] || msg['message']['bot_id']
                small
                  = link_to msg['message']['permalink'], target: '_blank', class: 'text-muted' do
                    = DateTime.strptime(msg['message']['ts'].to_s, '%s').strftime("%b %-d, %Y at %-I:%M %p")          
              = format_text(msg['message']['text'])
              small.text-muted Posted in #{team.first} #{msg['channel']} 
        - if msg['type'] == "file"
          .panel.panel-warning
            .panel-body
              p
                strong=> msg['file']['user']
                small.text-muted
                  = link_to msg['file']['permalink'], target: '_blank', class: 'text-muted' do
                    = DateTime.strptime(msg['file']['timestamp'].to_s, '%s').strftime("%b %-d, %Y at %-I:%M %p")
              p= link_to msg['file']['name'], msg['file']['url_private_download']
              - if msg['file']['initial_comment'].present?
                p= format_text(msg['file']['initial_comment']['comment'])
              small.text-muted Posted in #{team.first} #{msg['file']['channels'].to_sentence}

p
  br
  p= link_to "https://slack.com/oauth/authorize?scope=stars%3Aread&client_id=#{ENV['SLACK_APP_CLIENT_ID']}" do
    img alt="Sign in with Slack" height="40" src="https://platform.slack-edge.com/img/sign_in_with_slack.png" srcset="https://platform.slack-edge.com/img/sign_in_with_slack.png 1x, https://platform.slack-edge.com/img/sign_in_with_slack@2x.png 2x" width="172"
  br

- if cookies[:ss_access_tokens].present?
  p= link_to "Logout of #{pluralize(@all_tokens.length, 'account')}", clear_path, class: 'btn btn-danger btn-sm'
  br  

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    title Slackstar
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta http-equiv="x-ua-compatible" content="ie=edge"
    meta name="description" content="See all of your starred messages in Slack in one place."
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'
    = stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/todc-bootstrap/3.3.6-3.3.6/css/bootstrap-theme.min.css'
    = stylesheet_link_tag    '//cdnjs.cloudflare.com/ajax/libs/todc-bootstrap/3.3.6-3.3.6/css/todc-bootstrap.min.css'
  body
    .container-fluid
      - if @error.present?
        .alert.alert-danger Error: #{@error}
      = yield
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'